general {
    hide_cursor = true
}

background {
    monitor =
    path = ~/.config/everforest/wallpapers/fog-forest-1920x1080.png
    color = rgb(1e2326)
    blur_passes = 2
    blur_size = 5
    noise = 0.008
    contrast = 0.92
    brightness = 0.62
    vibrancy = 0.12
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(d3c6aa)
    font_family = CaskaydiaMono Nerd Font Mono
    font_size = 76
    position = 0, 150
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %B %d"
    color = rgb(a7c080)
    font_family = CaskaydiaMono Nerd Font Mono
    font_size = 18
    position = 0, 88
    halign = center
    valign = center
}

label {
    monitor =
    text =   $USER
    color = rgb(83c092)
    font_family = CaskaydiaMono Nerd Font Mono
    font_size = 16
    position = 0, -25
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 340, 54
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.32
    dots_center = true
    outer_color = rgb(374145)
    inner_color = rgba(272e33dd)
    font_color = rgb(d3c6aa)
    fade_on_empty = false
    placeholder_text = <span foreground="##D3C6AA">Password</span>
    fail_text = <span foreground="##E67E80">$FAIL</span>
    check_color = rgb(dbbc7f)
    fail_color = rgb(e67e80)
    capslock_color = rgb(e69875)
    position = 0, -92
    halign = center
    valign = center
}
