# monitor
monitor=eDP-1,disable
monitor=HDMI-A-2,1920x1080@100,0x0,1.25
# variables
$mod = SUPER

# startup
source = ~/.config/hypr/autostart.conf

# keybinds
source = ~/.config/hypr/keybinds.conf

# appearance
source = ~/.config/hypr/look.conf

# environment
env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORM,wayland
env = MOZ_ENABLE_WAYLAND,1



