# Hyprland — Everforest Dark Hard

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/decoration.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/rules.conf
source = ~/.config/hypr/keybinds.conf

$mod = SUPER

env = XCURSOR_THEME,Bibata-Everforest
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = MOZ_ENABLE_WAYLAND,1
env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,auto

input {
    kb_layout = us
    follow_mouse = 1
    repeat_delay = 300
    repeat_rate = 35

    touchpad {
        tap-to-click = true
        disable_while_typing = true
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

dwindle {
    preserve_split = true
    smart_split = false
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vrr = 0
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}

exec-once = mkdir -p ~/Pictures/Screenshots
exec-once = ~/.local/bin/hypr-display-watch
exec-once = ~/.local/bin/everforest-wallpaper
exec-once = ~/.local/bin/everforest-waybar --start
exec-once = ~/.local/bin/everforest-lock-on-start
exec-once = dunst
exec-once = hypridle
exec-once = pgrep -x xfce-polkit || /usr/libexec/xfce-polkit
