$mod = SUPER

# terminal
bind = $mod, RETURN, exec, ghostty

# launcher
bind = $mod, SPACE, exec, wofi --show drun

# close window
bind = $mod, Q, killactive

# reload config
bind = $mod SHIFT, R, exec, hyprctl reload

# lock
bind = $mod, L, exec, hyprlock

# screenshots
bind = $mod SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy


# workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3

bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2

