general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(89b4faff)
    col.inactive_border = rgba(45475aff)
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 6
        passes = 3
    }

    shadow {
        enabled = true
    }
}

animations {
    enabled = yes

    animation = windows, 1, 4, default
    animation = workspaces, 1, 4, default
}

